services:
  n8n_api:
    image: n8nio/n8n:${N8N_VERSION}
    env_file:
      - n8n.env
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - gmorang_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`) && PathPrefix(`/n8n`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.routers.n8n.priority=10"
      - "traefik.http.routers.n8n.service=n8n"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.middlewares.n8n-stripprefix.stripprefix.prefixes=/n8n"
      - "traefik.http.routers.n8n.middlewares=n8n-stripprefix"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s

  n8n_worker:
    image: n8nio/n8n:${N8N_VERSION}
    command: worker
    env_file:
      - n8n.env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - gmorang_network
    restart: unless-stopped
    depends_on:
      n8n_api:
        condition: service_healthy

  n8n_webhook:
    image: n8nio/n8n:${N8N_VERSION}
    command: webhook
    env_file:
      - n8n.env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      gmorang_network:
        aliases:
          - n8nwebhook
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n_webhook.rule=Host(`${N8N_HOST}`) && (PathPrefix(`/webhook`) || PathPrefix(`/webhook-test`) || PathPrefix(`/webhook-wait`))"
      - "traefik.http.routers.n8n_webhook.entrypoints=web"
      - "traefik.http.routers.n8n_webhook.priority=10"
      - "traefik.http.routers.n8n_webhook.service=n8n_webhook"
      - "traefik.http.services.n8n_webhook.loadbalancer.server.port=5678"
      - "traefik.http.middlewares.n8n_webhook-stripprefix.stripprefix.prefixes=/webhook"
      - "traefik.http.routers.n8n_webhook.middlewares=n8n_webhook-stripprefix"
    restart: unless-stopped
    depends_on:
      n8n_api:
        condition: service_healthy

volumes:
  n8n_data:
