services:
  traefik:
    extends:
      file: ./services/traefik/docker-compose.yml
      service: traefik

  postgres:
    extends:
      file: ./databases/postgres/docker-compose.yml
      service: postgres
    hostname: postgres
    networks:
      - gmorang_network

  evolution:
    extends:
      file: ./services/evolution/docker-compose.yml
      service: evolution
    hostname: evolution
    networks:
      - gmorang_network
    depends_on:
      - redis
      - postgres

  redis:
    extends:
      file: ./databases/redis/docker-compose.yml
      service: redis
    hostname: redis
    networks:
      - gmorang_network

  n8n_api:
    extends:
      file: ./services/n8n/docker-compose.yml
      service: n8n_api
    hostname: n8n_api
    networks:
      - gmorang_network
    depends_on:
      - postgres
      - redis

  n8n_worker:
    extends:
      file: ./services/n8n/docker-compose.yml
      service: n8n_worker
    hostname: n8n_worker
    networks:
      - gmorang_network

    depends_on:
      - n8n_api

  n8n_webhook:
    extends:
      file: ./services/n8n/docker-compose.yml
      service: n8n_webhook
    hostname: n8n_webhook
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n_webhook.rule=Host(`${N8N_HOST}`) && (PathPrefix(`/webhook`) || PathPrefix(`/webhook-test`) || PathPrefix(`/webhook-wait`))"
      - "traefik.http.routers.n8n_webhook.entrypoints=websecure"
      - "traefik.http.routers.n8n_webhook.tls=true"
      - "traefik.http.routers.n8n_webhook.tls.certresolver=letsencrypt"
      - "traefik.http.routers.n8n_webhook.priority=100"
      - "traefik.http.routers.n8n_webhook.service=n8n_webhook"
      - "traefik.http.services.n8n_webhook.loadbalancer.server.port=5678"
    networks:
      - gmorang_network
    depends_on:
      - n8n_api

networks:
  gmorang_network:
    name: gmorang_network
    driver: bridge

volumes:
  n8n_data:
    name: n8n_data
  redis_data:
    name: redis_data
  postgres_data:
    name: postgres_data
  evolution_data:
    name: evolution_data
