services:
  redis:
    image: redis:8.0.1-bookworm
    env_file:
      - redis.env
    command: ["sh", "-lc", 'exec redis-server --requirepass "$REDIS_PASSWORD"']
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - gmorang_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
volumes:
  redis_data:
